'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'

type Plan = { id: string; name: string; status: string; site: { name: string; client: { displayName: string } } }
type Member = { id: string; name: string | null; email: string; role: string }
type Visit = { id: string; scheduledStart: string; scheduledEnd: string; status: string; version: number; requiredWorkers: number; site: { name: string; city: string; client: { displayName: string } }; job: { name: string }; assignments: Array<{ status: string; user: Member }> }

async function api<T>(url: string, options?: RequestInit): Promise<T> {
  const response = await fetch(url, { credentials: 'include', cache: 'no-store', ...options }); const body = await response.json()
  if (!response.ok || !body.ok) throw new Error(body.error ?? 'Request failed'); return body.data as T
}

function localInput(date: Date) { const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16) }

export default function ScheduleBoard({ canManage }: { canManage: boolean }) {
  const [visits, setVisits] = useState<Visit[]>([]); const [plans, setPlans] = useState<Plan[]>([]); const [team, setTeam] = useState<Member[]>([])
  const [view, setView] = useState<'list' | 'day' | 'week'>('list'); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false)
  const [notice, setNotice] = useState<string | null>(null); const [showCreate, setShowCreate] = useState(false)
  const [draft, setDraft] = useState({ servicePlanId: '', name: '', startAt: localInput(new Date(Date.now() + 86_400_000)), durationMinutes: 120, frequency: 'once', weekdays: [1, 3, 5] as number[], assigneeIds: [] as string[] })
  const range = useMemo(() => ({ from: new Date(Date.now() - 7 * 86_400_000).toISOString(), to: new Date(Date.now() + 90 * 86_400_000).toISOString() }), [])
  const refresh = useCallback(async () => { setLoading(true); try { const [v, p, t] = await Promise.all([api<Visit[]>(`/api/visits?from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`), api<Plan[]>('/api/service-plans'), api<Member[]>('/api/team')]); setVisits(v); setPlans(p.filter((plan) => plan.status === 'published')); setTeam(t); setDraft((d) => ({ ...d, servicePlanId: d.servicePlanId || p.find((plan) => plan.status === 'published')?.id || '' })) } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not load schedule.') } finally { setLoading(false) } }, [range])
  useEffect(() => { void refresh() }, [refresh])

  async function createJob(event: FormEvent) { event.preventDefault(); setBusy(true); try { const recurrence = draft.frequency === 'weekly' ? { frequency: 'weekly', interval: 1, weekdays: draft.weekdays } : draft.frequency === 'daily' ? { frequency: 'daily', interval: 1 } : { frequency: 'once' }; await api('/api/jobs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ servicePlanId: draft.servicePlanId, name: draft.name, startAt: new Date(draft.startAt).toISOString(), durationMinutes: draft.durationMinutes, recurrence, assigneeIds: draft.assigneeIds }) }); setNotice('Job scheduled and visits generated.'); setShowCreate(false); await refresh() } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not schedule job.') } finally { setBusy(false) } }
  const grouped = useMemo(() => visits.reduce<Record<string, Visit[]>>((acc, visit) => { const key = new Date(visit.scheduledStart).toLocaleDateString('en-IE', { weekday: 'long', day: 'numeric', month: 'short' }); (acc[key] ??= []).push(visit); return acc }, {}), [visits])

  return <main className="page-shell schedule-page"><header className="page-header schedule-hero"><div><span className="eyebrow">Dispatch control</span><h1>Smart schedule</h1><p className="muted">Recurring work becomes accountable visits with people, status and immutable instructions.</p></div>{canManage ? <button className="btn-primary" onClick={() => setShowCreate((value) => !value)}>{showCreate ? 'Close' : '+ Schedule job'}</button> : null}</header>
    <section className="schedule-toolbar"><div className="segmented-control">{(['list','day','week'] as const).map((item) => <button key={item} className={view === item ? 'selected' : ''} onClick={() => setView(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div><div className="schedule-legend"><span className="dot scheduled"/>Scheduled <span className="dot acknowledged"/>Acknowledged <span className="dot completed"/>Completed</div></section>
    {notice ? <div className="toast success" role="status">{notice}<button className="notice-close" onClick={() => setNotice(null)}>×</button></div> : null}
    {showCreate ? <form className="schedule-create" onSubmit={createJob}><div><span className="eyebrow">Published work</span><h2>Create recurring job</h2></div><label>Service plan<select required value={draft.servicePlanId} onChange={(e)=>setDraft({...draft,servicePlanId:e.target.value})}><option value="">Select published plan</option>{plans.map((plan)=><option key={plan.id} value={plan.id}>{plan.site.client.displayName} · {plan.site.name} · {plan.name}</option>)}</select></label><label>Job name<input required value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value})}/></label><label>First visit<input type="datetime-local" required value={draft.startAt} onChange={(e)=>setDraft({...draft,startAt:e.target.value})}/></label><label>Frequency<select value={draft.frequency} onChange={(e)=>setDraft({...draft,frequency:e.target.value})}><option value="once">Once</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><label>Duration (minutes)<input type="number" min="1" value={draft.durationMinutes} onChange={(e)=>setDraft({...draft,durationMinutes:Number(e.target.value)})}/></label><label>Team<select multiple value={draft.assigneeIds} onChange={(e)=>setDraft({...draft,assigneeIds:Array.from(e.target.selectedOptions).map((option)=>option.value)})}>{team.map((member)=><option key={member.id} value={member.id}>{member.name ?? member.email}</option>)}</select></label><button className="btn-primary" disabled={busy || !plans.length}>Generate visits</button></form> : null}
    {loading ? <section className="card empty-state">Loading schedule…</section> : null}
    {!loading ? <section className={`schedule-board ${view}`}><aside className="schedule-summary"><strong>{visits.length}</strong><span>visits in range</span><div><b>{visits.filter((visit)=>visit.status==='completed').length}</b> complete</div><div><b>{visits.filter((visit)=>!visit.assignments.length).length}</b> unassigned</div></aside><div className="schedule-days">{Object.entries(grouped).map(([day, rows])=><section className="schedule-day" key={day}><header><h2>{day}</h2><span>{rows.length} visit{rows.length===1?'':'s'}</span></header>{rows.map((visit)=><article className="visit-card" key={visit.id} data-status={visit.status}><time>{new Date(visit.scheduledStart).toLocaleTimeString('en-IE',{hour:'2-digit',minute:'2-digit'})}</time><div><strong>{visit.site.client.displayName}</strong><div>{visit.job.name} · {visit.site.name}</div><small>{visit.site.city} · {Math.round((new Date(visit.scheduledEnd).getTime()-new Date(visit.scheduledStart).getTime())/60000)} min</small></div><div className="visit-team">{visit.assignments.length?visit.assignments.map((a)=><span key={a.user.id} title={a.user.email}>{(a.user.name??a.user.email).split(' ').map((p)=>p[0]).slice(0,2).join('')}</span>):<em>Unassigned</em>}</div><span className={`status-badge ${visit.status==='completed'?'Completed':'Pending'}`}>{visit.status.replace('_',' ')}</span></article>)}</section>)}{!visits.length?<div className="card empty-state">No visits in this period. Publish a plan, then schedule the job.</div>:null}</div></section> : null}
  </main>
}
