import { Button, Card, EmptyState, PageHeader, Screen } from '@/components/ui';
import { apiFetch } from '@/lib/api';
import { useAuth } from '@/lib/auth-context';
import { colors } from '@/lib/theme';
import type { Notice } from '@/lib/types';
import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, TextInput, View } from 'react-native';

export default function InboxScreen() {
  const { session } = useAuth(); const [items, setItems] = useState<Notice[]>([]); const [loading, setLoading] = useState(true); const [notes, setNotes] = useState<Record<string, string>>({}); const [message, setMessage] = useState('');
  const refresh = useCallback(async () => { if (!session) return; setLoading(true); try { const data = await apiFetch<{ items: Notice[] }>(session, '/api/operational-notices?scope=mine'); setItems(data.items); } finally { setLoading(false); } }, [session]);
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  async function acknowledge(item: Notice) { if (!session) return; await apiFetch(session, `/api/operational-notices/${item.id}/receipt`, { method: 'PATCH', body: JSON.stringify({ action: 'acknowledged', acknowledgement: notes[item.id]?.trim() || null }) }); setMessage('Update confirmed.'); await refresh(); }
  const pending = items.filter((item) => item.requiresAcknowledgement && !item.recipients[0]?.acknowledgedAt).length;
  return <Screen><PageHeader eyebrow="Operational updates" title={pending ? `Inbox · ${pending} to confirm` : 'Inbox'} subtitle="Important changes stay linked to the right site and visit." />{message ? <Text style={styles.success}>{message}</Text> : null}
    {loading ? <ActivityIndicator color={colors.primary} size="large" /> : items.length ? items.map((item) => { const receipt = item.recipients[0]; return <Card key={item.id} style={[styles.notice, item.priority === 'critical' && styles.critical, receipt?.acknowledgedAt && styles.read]}><View style={styles.meta}><Text style={[styles.priority, styles[`priority_${item.priority}`]]}>{item.priority}</Text><Text style={styles.type}>{item.type.replaceAll('_', ' ')}</Text><Text style={styles.date}>{new Intl.DateTimeFormat('en-IE', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(item.publishedAt))}</Text></View><Text style={styles.title}>{item.title}</Text><Text style={styles.body}>{item.body}</Text>{item.site ? <Text style={styles.context}>{item.site.client.displayName} · {item.site.name}</Text> : null}<Text style={styles.from}>From {item.createdBy.name ?? item.createdBy.email}</Text>{item.requiresAcknowledgement && !receipt?.acknowledgedAt ? <><TextInput value={notes[item.id] ?? ''} onChangeText={(value) => setNotes((current) => ({ ...current, [item.id]: value }))} placeholder="Optional note to the manager" style={styles.input} /><Button title="Acknowledge" onPress={() => void acknowledge(item)} /></> : receipt?.acknowledgedAt ? <Text style={styles.ack}>✓ Acknowledged</Text> : null}</Card>; }) : <EmptyState title="You are all caught up" body="Important changes and instructions will appear here." />}
  </Screen>;
}
const styles = StyleSheet.create({ success: { padding: 12, borderRadius: 12, color: colors.success, fontWeight: '800', backgroundColor: colors.primarySoft }, notice: { borderLeftWidth: 5, borderLeftColor: colors.warning }, critical: { borderLeftColor: colors.danger, backgroundColor: '#FFF8F7' }, read: { borderLeftColor: colors.border, opacity: 0.78 }, meta: { flexDirection: 'row', alignItems: 'center', gap: 8 }, priority: { paddingHorizontal: 7, paddingVertical: 3, borderRadius: 99, overflow: 'hidden', fontSize: 9, fontWeight: '900', textTransform: 'uppercase', backgroundColor: '#EEF1F5' }, priority_low: { color: colors.muted }, priority_normal: { color: colors.primary }, priority_high: { color: colors.warning, backgroundColor: '#FFF0DD' }, priority_critical: { color: colors.danger, backgroundColor: '#FDECEA' }, type: { flex: 1, color: colors.muted, fontSize: 10, fontWeight: '700', textTransform: 'capitalize' }, date: { color: colors.muted, fontSize: 9 }, title: { color: colors.ink, fontSize: 18, fontWeight: '900' }, body: { color: colors.ink, fontSize: 14, lineHeight: 21 }, context: { color: colors.primary, fontSize: 12, fontWeight: '800', padding: 9, borderRadius: 9, backgroundColor: colors.primarySoft }, from: { color: colors.muted, fontSize: 11 }, input: { minHeight: 45, borderWidth: 1, borderColor: colors.border, borderRadius: 11, paddingHorizontal: 12 }, ack: { color: colors.success, fontWeight: '800' } });
