import { Button, Card, EmptyState, PageHeader, Screen } from '@/components/ui';
import { colors } from '@/lib/theme';
import { useVisits } from '@/lib/use-visits';
import { router } from 'expo-router';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';

export default function WorkScreen() {
  const { visits, loading, offline } = useVisits();
  const actionable = visits.filter((visit) => !['completed', 'cancelled'].includes(visit.status));
  const active = actionable.find((visit) => visit.status === 'in_progress' || visit.timeEntries?.some((entry) => entry.status === 'running' && !entry.endedAt));
  const pendingAcknowledgements = actionable.filter((visit) => visit.assignments?.some((assignment) => assignment.status === 'assigned' || assignment.status === 'notified'));
  const issues = actionable.flatMap((visit) => (visit.incidents ?? []).filter((incident) => !['resolved', 'closed'].includes(incident.status)).map((incident) => ({ ...incident, visit })));
  const next = active ?? actionable[0];

  return <Screen><PageHeader eyebrow={offline ? 'Saved work package' : 'Field control'} title={active ? 'Active work' : 'My work'} subtitle={active ? 'Keep the visit evidence and timer together.' : 'Start from the one task that needs you next.'} />
    {loading ? <ActivityIndicator color={colors.primary} size="large" /> : <>
      {next ? <Card style={[styles.primary, active && styles.primaryActive]}><Text style={styles.kicker}>{active ? 'In progress now' : 'Next assigned visit'}</Text><Text style={styles.client}>{next.site.client.displayName}</Text><Text style={styles.visit}>{next.job?.name ?? next.site.name}</Text><Text style={styles.meta}>{formatWindow(next.scheduledStart, next.scheduledEnd)} · {next.site.name}</Text><Text style={styles.meta}>{next.site.addressLine1}, {next.site.city}</Text><Button title={active ? 'Continue visit' : 'Open work package'} onPress={() => router.push(`/visit/${next.id}`)} /></Card> : <EmptyState title="No active work" body="Your current and future assigned visits will stay here, including when you are offline." />}
      {pendingAcknowledgements.length ? <Card style={styles.attention}><Text style={styles.attentionTitle}>{pendingAcknowledgements.length} schedule change{pendingAcknowledgements.length === 1 ? '' : 's'} to confirm</Text><Text style={styles.attentionCopy}>Open the visit to accept it or explain why you cannot take it.</Text>{pendingAcknowledgements.slice(0, 2).map((visit) => <Pressable key={visit.id} onPress={() => router.push(`/visit/${visit.id}`)}><Text style={styles.link}>{visit.site.client.displayName} · {formatWindow(visit.scheduledStart, visit.scheduledEnd)} →</Text></Pressable>)}</Card> : null}
      {issues.length ? <View style={styles.section}><Text style={styles.sectionTitle}>Open problems</Text>{issues.map(({ id, title, severity, visit }) => <Pressable key={id} onPress={() => router.push(`/visit/${visit.id}`)}><Card style={styles.issue}><View><Text style={styles.issueTitle}>{title}</Text><Text style={styles.issueMeta}>{visit.site.client.displayName} · {visit.site.name}</Text></View><Text style={styles.severity}>{severity}</Text></Card></Pressable>)}</View> : null}
      {actionable.length > 1 ? <View style={styles.section}><Text style={styles.sectionTitle}>Up next</Text>{actionable.filter((visit) => visit.id !== next?.id).slice(0, 4).map((visit) => <Pressable key={visit.id} onPress={() => router.push(`/visit/${visit.id}`)}><Card style={styles.row}><View style={styles.time}><Text style={styles.timeMain}>{formatTime(visit.scheduledStart)}</Text><Text style={styles.timeEnd}>{formatTime(visit.scheduledEnd)}</Text></View><View style={styles.rowBody}><Text style={styles.rowTitle}>{visit.site.client.displayName}</Text><Text style={styles.rowMeta}>{visit.job?.name ?? visit.site.name} · {visit.site.city}</Text></View><Text style={styles.arrow}>›</Text></Card></Pressable>)}</View> : null}
    </>}
  </Screen>;
}

function formatTime(value: string) { return new Intl.DateTimeFormat('en-IE', { hour: '2-digit', minute: '2-digit' }).format(new Date(value)); }
function formatWindow(start: string, end: string) { return `${formatTime(start)}–${formatTime(end)}`; }
const styles = StyleSheet.create({
  primary: { backgroundColor: colors.ink, borderColor: colors.ink, gap: 7 }, primaryActive: { backgroundColor: '#123B34' }, kicker: { color: '#A7E5CE', fontSize: 11, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.8 }, client: { color: '#fff', fontSize: 23, fontWeight: '900' }, visit: { color: '#D9E5EB', fontSize: 15, fontWeight: '700' }, meta: { color: '#C8D7DF', fontSize: 12, lineHeight: 18 }, attention: { backgroundColor: '#FFF8EC', borderColor: '#EBC67A' }, attentionTitle: { color: colors.warning, fontSize: 16, fontWeight: '900' }, attentionCopy: { color: colors.ink, fontSize: 13, lineHeight: 19 }, link: { color: colors.primary, paddingTop: 3, fontWeight: '800', fontSize: 13 }, section: { gap: 10 }, sectionTitle: { color: colors.ink, fontSize: 19, fontWeight: '900' }, issue: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderLeftWidth: 4, borderLeftColor: colors.danger }, issueTitle: { color: colors.ink, fontWeight: '900', fontSize: 15 }, issueMeta: { color: colors.muted, fontSize: 12, marginTop: 3 }, severity: { color: colors.danger, textTransform: 'uppercase', fontSize: 10, fontWeight: '900' }, row: { flexDirection: 'row', alignItems: 'center', gap: 12 }, time: { width: 54 }, timeMain: { color: colors.primary, fontSize: 15, fontWeight: '900' }, timeEnd: { color: colors.muted, fontSize: 11 }, rowBody: { flex: 1 }, rowTitle: { color: colors.ink, fontSize: 15, fontWeight: '900' }, rowMeta: { color: colors.muted, fontSize: 12, marginTop: 3 }, arrow: { color: colors.primary, fontSize: 28 },
});
