import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/login')
  await page.fill('input[type="email"]', 'admin@ds.ie')
  await page.fill('input[type="password"]', 'password123')
  await page.click('button[type="submit"]')
  await page.waitForURL(/\/home/)
})

test('manager can move through the operational control centre', async ({ page }) => {
  await expect(page.getByText('Operations command centre')).toBeVisible()

  await page.goto('/clients', { waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('heading', { name: 'Clients', exact: true, level: 1 })).toBeVisible()
  const clientAccounts = page.getByRole('region', { name: 'Client accounts' })
  await expect(clientAccounts).toBeVisible()
  const firstClient = clientAccounts.getByRole('link').first()
  await expect(firstClient).toBeVisible()
  await firstClient.click()
  await expect(page).toHaveURL(/\/clients\/[^/]+$/)
  await page.goBack()

  await page.goto('/work-orders', { waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('heading', { name: 'Work orders', exact: true, level: 1 })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Work order register', exact: true, level: 2 })).toBeVisible()
  await page.getByRole('button', { name: 'Filters', exact: true }).first().click()
  const filterDialog = page.getByRole('dialog', { name: 'Filters' })
  const statusFilter = filterDialog.getByRole('combobox', { name: 'Work order status', exact: true })
  await expect(statusFilter).toBeVisible()
  await expect(statusFilter).toContainText('All statuses')
  await filterDialog.getByRole('button', { name: 'Apply', exact: true }).click()
  await expect(filterDialog).toHaveCount(0)
  await page.getByRole('table', { name: 'Work orders' }).getByRole('button').first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)

  await page.goto('/operations', { waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: 'Sites & areas', exact: true }).click()
  await page.locator('.operations-row-button').first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')

  await page.goto('/schedule', { waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('heading', { name: 'Schedule', exact: true, level: 1 })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Week' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Today' })).toBeVisible()
  await page.locator('header').getByRole('button', { name: '+ Add visit', exact: true }).click()
  const addVisitDialog = page.getByRole('dialog', { name: 'Add visit' })
  await expect(addVisitDialog).toBeVisible()
  await expect(addVisitDialog.getByText(/Add one occurrence without changing the client’s recurring service/i)).toBeVisible()
  await addVisitDialog.getByRole('button', { name: 'Close', exact: true }).click()

  await page.goto('/quality', { waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('heading', { name: 'Quality control', exact: true, level: 1 })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Control centre' })).toBeVisible()

  await page.goto('/timesheets', { waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('heading', { name: 'Timesheets', exact: true, level: 1 })).toBeVisible()
  await expect(page.getByRole('button', { name: /Review time/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Payroll preview' })).toBeVisible()
})
