import { expect, test } from '@playwright/test'
import { createClientWithPublishedService, loginAsAdmin, uniqueLabel } from './helpers/operational-scenario'

test('quality assurance list is bounded, searchable and paginated', async ({ page }) => {
  await loginAsAdmin(page)
  await page.goto('/quality')

  const card = page.getByTestId('assurance-card')
  const viewport = page.getByTestId('assurance-viewport')
  await expect(card).toBeVisible()
  await expect(viewport).toBeVisible()
  await expect(card.getByRole('searchbox', { name: 'Search sites needing assurance' })).toBeVisible()

  const layout = await viewport.evaluate((element) => ({
    overflowY: getComputedStyle(element).overflowY,
    height: element.getBoundingClientRect().height,
  }))
  expect(layout.overflowY).toBe('auto')
  expect(layout.height).toBeLessThanOrEqual(445)
  await expect(card.locator('.pagination-bar')).toBeVisible()
})

test('failed inspection becomes a resolved and verified corrective action', async ({ page }) => {
  await loginAsAdmin(page)
  const scenario = await createClientWithPublishedService(page)
  const finding = uniqueLabel('Floor residue requires cleaning')
  await page.goto('/quality')
  await page.getByRole('button', { name: /New inspection|Inspect site|Run inspection/i }).click()
  await page.getByRole('combobox', { name: 'Client site', exact: true }).click()
  await page.getByRole('option').filter({ hasText: scenario.name }).click()
  const checks = page.locator('.quality-check')
  await expect(checks.first()).toBeVisible()
  for (const check of await checks.all()) await check.getByRole('button', { name: 'Pass', exact: true }).click()
  await checks.first().getByRole('button', { name: 'Issue', exact: true }).click()
  await checks.first().getByRole('textbox').fill(finding)
  await page.getByRole('button', { name: 'Submit inspection & open actions', exact: true }).click()
  await expect(page.getByRole('status')).toContainText(/Inspection .* saved/)
  const action = page.locator('.quality-action-card').filter({ hasText: finding })
  await action.getByRole('button', { name: 'Accept', exact: true }).click()
  await expect(action).toContainText('accepted')
  await action.getByRole('button', { name: 'Start', exact: true }).click()
  await expect(action).toContainText('in progress')
  await action.getByRole('button', { name: 'Resolve', exact: true }).click()
  const resolve = page.getByRole('dialog', { name: 'Resolve action' })
  await expect(resolve.getByRole('button', { name: 'Confirm resolved' })).toBeDisabled()
  await resolve.getByRole('textbox').fill('Floor recleaned and photographed for review.')
  await resolve.getByRole('button', { name: 'Confirm resolved' }).click()
  await expect(resolve).toBeHidden()
  await page.reload()
  await page.getByRole('button', { name: /Corrective actions/i }).click()
  await expect(action).toContainText('resolved')
  await action.getByRole('button', { name: 'Verify fix' }).click()
  const verify = page.getByRole('dialog', { name: 'Verify fix' })
  await verify.getByRole('textbox').fill('Inspected the floor; no residue remains.')
  await verify.getByRole('button', { name: 'Confirm verified' }).click()
  await expect(verify).toBeHidden()
  await page.reload()
  await page.getByRole('button', { name: /Corrective actions/i }).click()
  await expect(action).toContainText('verified')
})