'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import DetailDialog from '../ui/DetailDialog'
import ListControls from '../ui/ListControls'
import { formatDuration } from '../../lib/duration'

type Job = {
  id: string; name: string; status: string; startDate: string; endDate?: string | null; defaultDurationMin: number; requiredWorkers: number
  site: { name: string; city: string; client: { displayName: string } }
  servicePlanVersion?: { versionNumber: number } | null
  _count: { visits: number }
  operationalVisits?: number
  coverageGaps?: number
}
async function getJobs(): Promise<Job[]> { const response = await fetch('/api/jobs', { credentials: 'include', cache: 'no-store' }); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.error ?? 'Could not load work orders.'); return body.data as Job[] }
function formatDate(value?: string | null) { return value ? new Intl.DateTimeFormat('en-IE', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)) : 'Ongoing' }

export default function WorkOrdersWorkspace() {
  const [jobs, setJobs] = useState<Job[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState<'all' | 'active' | 'paused'>('all'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState<string | null>(null)
  const refresh = useCallback(async () => { setLoading(true); try { setJobs(await getJobs()) } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not load work orders.') } finally { setLoading(false) } }, [])
  useEffect(() => { void refresh() }, [refresh])
  const visible = useMemo(() => { const needle = query.trim().toLowerCase(); return jobs.filter((job) => (status === 'all' || job.status === status) && (!needle || `${job.name} ${job.site.name} ${job.site.client.displayName}`.toLowerCase().includes(needle)) && (!from || job.startDate.slice(0,10) >= from) && (!to || job.startDate.slice(0,10) <= to)) }, [from, jobs, query, status, to])
  const selected = useMemo(() => jobs.find((job) => job.id === selectedId) ?? null, [jobs, selectedId])
  const active = jobs.filter((job) => job.status === 'active').length
  const visits = jobs.reduce((total, job) => total + (job.operationalVisits ?? job._count.visits), 0)
  const coverageGaps = jobs.reduce((total, job) => total + (job.coverageGaps ?? 0), 0)

  return <main className="page-shell manager-page">
    <header className="manager-header"><div><span className="eyebrow">Operational delivery</span><h1>Work orders</h1><p className="muted">The live bridge between a contracted service plan and the visits your team executes.</p></div><a className="btn-primary" href="/schedule">+ Schedule work</a></header>
    <section className="manager-kpis" aria-label="Work order overview"><article><span>Active work orders</span><strong>{active}</strong><small>Currently generating work</small></article><article><span>Operational visits</span><strong>{visits}</strong><small>Cancelled and missed history excluded</small></article><article className={coverageGaps ? 'attention-card' : ''}><span>Coverage gaps</span><strong>{coverageGaps}</strong><small>Visits below required cleaner count</small></article><article className="manager-kpi-action"><strong>Dispatch from the schedule</strong><small>Resolve coverage, timing and assignment exceptions.</small></article></section>
    {message ? <div className="toast error" role="alert">{message}<button className="notice-close" onClick={() => setMessage(null)}>×</button></div> : null}
    <div className="work-orders-standard-filter"><ListControls query={query} onQueryChange={setQuery} from={from} to={to} onFromChange={setFrom} onToChange={setTo} placeholder="Search client, site or work order…" hasActiveFilters={Boolean(query.trim() || from || to || status !== 'all')} onClear={() => { setQuery(''); setFrom(''); setTo(''); setStatus('all') }} options={[{ label: 'Work order status', value: status, defaultValue: 'all', choices: [{ value: 'all', label: 'All statuses' }, { value: 'active', label: 'Active' }, { value: 'paused', label: 'Paused' }], onChange: (value) => setStatus(value as typeof status) }]} /></div>
    <section className="manager-workspace manager-workspace-single"><div className="manager-list card"><div className="manager-list-toolbar work-orders-toolbar"><div><h2>Work order register</h2><span className="muted">{loading ? 'Loading…' : `${visible.length} result${visible.length === 1 ? '' : 's'}`}</span></div><ListControls query={query} onQueryChange={setQuery} from={from} to={to} onFromChange={setFrom} onToChange={setTo} placeholder="Search client, site or work order…" hasActiveFilters={Boolean(query.trim() || from || to || status !== 'all')} onClear={() => { setQuery(''); setFrom(''); setTo(''); setStatus('all') }} /></div><div className="filter-chips" aria-label="Filter work orders"><button className={status === 'all' ? 'selected' : ''} onClick={() => setStatus('all')}>All</button><button className={status === 'active' ? 'selected' : ''} onClick={() => setStatus('active')}>Active</button><button className={status === 'paused' ? 'selected' : ''} onClick={() => setStatus('paused')}>Paused</button></div><div className="manager-table work-orders-table scroll-list" role="table" aria-label="Work orders"><div className="manager-table-head" role="row"><span>Work order</span><span>Visits</span><span>Coverage</span><span>Status</span></div>{visible.map((job) => <button className={selected?.id === job.id ? 'manager-row selected' : 'manager-row'} key={job.id} onClick={() => setSelectedId(job.id)}><span><b>{job.name}</b><small>{job.site.client.displayName} · {job.site.name}</small></span><span>{job.operationalVisits ?? job._count.visits}</span><span className={(job.coverageGaps ?? 0) ? 'warning-text' : ''}>{job.coverageGaps ?? 0} gap{(job.coverageGaps ?? 0) === 1 ? '' : 's'}</span><span className={`status-badge ${job.status === 'active' ? 'Completed' : 'Pending'}`}>{job.status}</span></button>)}{!loading && !visible.length ? <div className="empty-state">No work orders match this view.</div> : null}</div></div></section>
    <DetailDialog open={Boolean(selected)} title={selected?.name ?? 'Work order'} eyebrow="Work order" onClose={() => setSelectedId(null)}>{selected ? <div className="manager-detail"><span className={`status-badge ${selected.status === 'active' ? 'Completed' : 'Pending'}`}>{selected.status}</span><dl><div><dt>Client</dt><dd>{selected.site.client.displayName}</dd></div><div><dt>Site</dt><dd>{selected.site.name}, {selected.site.city}</dd></div><div><dt>Operational visits</dt><dd>{selected.operationalVisits ?? selected._count.visits}</dd></div><div><dt>Coverage gaps</dt><dd>{selected.coverageGaps ?? 0}</dd></div><div><dt>Plan version</dt><dd>v{selected.servicePlanVersion?.versionNumber ?? '—'}</dd></div><div><dt>Default visit</dt><dd>{formatDuration(selected.defaultDurationMin)} · {selected.requiredWorkers} worker{selected.requiredWorkers === 1 ? '' : 's'}</dd></div><div><dt>Service through</dt><dd>{formatDate(selected.endDate)}</dd></div></dl><a className="btn-primary full-width" href="/schedule">Open dispatch calendar →</a><a className="btn-secondary full-width" href="/operations">Review service setup →</a></div> : null}</DetailDialog>
  </main>
}
