'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'

type Visit = { id: string; status: string; scheduledStart: string; scheduledEnd: string; site: { name: string; city: string; client: { displayName: string } }; assignments: Array<{ status: string; user: { id: string; name?: string | null; email: string } }> }
type Client = { id: string; displayName: string; status: string; _count: { sites: number } }
type TimeEntry = { id: string; status: string; disputes: Array<{ status: string }> }
type SupplyResponse = { total: number; items: Array<{ id: string; status: string; priority: string; dueAt?: string | null }> }
type FieldSummary = { summary: { openIncidents: number; criticalIncidents: number; needsReview: number; blocked: number } }
type QualitySummary = { summary: { openActions: number; overdueActions: number; criticalActions: number } }
const ACTIVE_HOME_ASSIGNMENTS = new Set(['assigned', 'notified', 'seen', 'acknowledged'])

async function read<T>(url: string): Promise<T | null> { const response = await fetch(url, { credentials: 'include', cache: 'no-store' }); const body = await response.json().catch(() => null); return response.ok && body?.ok ? body.data as T : null }

export default function ManagerOverview() {
  const [visits, setVisits] = useState<Visit[]>([]); const [clients, setClients] = useState<Client[]>([]); const [entries, setEntries] = useState<TimeEntry[]>([]); const [supplies, setSupplies] = useState<SupplyResponse | null>(null); const [field, setField] = useState<FieldSummary | null>(null); const [quality, setQuality] = useState<QualitySummary | null>(null); const [loading, setLoading] = useState(true)
  const range = useMemo(() => { const start = new Date(); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1); return { from: start.toISOString(), to: end.toISOString() } }, [])
  const refresh = useCallback(async () => { setLoading(true); const [visitData, clientData, entryData, supplyData, fieldData, qualityData] = await Promise.all([read<Visit[]>(`/api/visits?from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`), read<Client[]>('/api/clients'), read<TimeEntry[]>('/api/time-entries'), read<SupplyResponse>('/api/supplies?limit=200'), read<FieldSummary>('/api/field-control'), read<QualitySummary>('/api/quality/control')]); setVisits(visitData ?? []); setClients(clientData ?? []); setEntries(entryData ?? []); setSupplies(supplyData); setField(fieldData); setQuality(qualityData); setLoading(false) }, [range])
  useEffect(() => { void refresh() }, [refresh])
  const unassigned = visits.filter((visit) => !visit.assignments.some((assignment) => ACTIVE_HOME_ASSIGNMENTS.has(assignment.status))).length
  const active = visits.filter((visit) => visit.status === 'in_progress').length
  const review = entries.filter((entry) => entry.status === 'needs_review' || entry.disputes.some((dispute) => dispute.status === 'open')).length
  const now = new Date()

  return <main className="page-shell manager-overview">
    <header className="manager-home-hero"><div><span className="eyebrow">Operations command centre</span><h1>Good morning</h1><p>See what needs a decision, dispatch work quickly, and keep service delivery moving.</p></div><div className="manager-home-actions"><a href="/schedule" className="btn-primary">Open schedule</a><a href="/operations" className="btn-secondary">Create service</a></div></header>
    <section className="command-metrics" aria-label="Today's operations"><a href="/schedule"><span>Visits today</span><strong>{loading ? '—' : visits.length}</strong><small>{active} in progress</small></a><a href="/schedule"><span>Unassigned work</span><strong>{loading ? '—' : unassigned}</strong><small>{unassigned ? 'Needs dispatch' : 'All work covered'}</small></a><a href="/timesheets"><span>Time to review</span><strong>{loading ? '—' : review}</strong><small>{review ? 'Needs a manager decision' : 'No time exceptions'}</small></a><a href="/clients"><span>Active clients</span><strong>{loading ? '—' : clients.filter((client) => client.status === 'active').length}</strong><small>{clients.reduce((sum, client) => sum + client._count.sites, 0)} sites on record</small></a></section>
    <section className="command-grid"><section className="card command-today"><header><div><span className="eyebrow">Today</span><h2>Dispatch board</h2></div><a href="/schedule">View full schedule →</a></header>{visits.length ? <div className="command-visit-list">{visits.slice(0, 6).map((visit) => <a href="/schedule" key={visit.id}><time>{new Date(visit.scheduledStart).toLocaleTimeString('en-IE', { hour: '2-digit', minute: '2-digit' })}</time><div><b>{visit.site.client.displayName}</b><span>{visit.site.name} · {visit.site.city}</span></div><span className={`status-badge ${visit.status === 'completed' ? 'Completed' : 'Pending'}`}>{visit.status.replace('_', ' ')}</span></a>)}</div> : <div className="empty-state">No visits scheduled for today.</div>}</section><aside className="card command-actions"><span className="eyebrow">Manager actions</span><h2>Keep the operation ahead</h2><a href="/schedule"><b>Schedule work</b><span>Assign the next visit or resolve an unassigned item.</span>→</a><a href="/clients"><b>Open client record</b><span>Review sites, contract relationships and contacts.</span>→</a><a href="/timesheets"><b>Review hours</b><span>Handle location flags or employee time challenges.</span>→</a><a href="/supplies"><b>Material control</b><span>Act on low stock before it stops a service.</span>→</a></aside></section>
    <section className="command-bottom"><article className="card"><span className="eyebrow">Live portfolio</span><h2>{clients.length} client record{clients.length === 1 ? '' : 's'}</h2><p className="muted">Clients, locations and service design stay connected to every work order, visit, stock count and quality record.</p><a className="btn-secondary" href="/clients">Manage clients</a></article><article className="card"><span className="eyebrow">Operational guardrails</span><h2>Every schedule change is visible</h2><p className="muted">Availability conflicts, assignment changes, evidence review and time disputes all retain their decision history.</p><a className="btn-secondary" href="/field-control">Open field control</a></article><article className="card command-date"><span>{now.toLocaleDateString('en-IE', { weekday: 'long' })}</span><strong>{now.getDate()}</strong><small>{now.toLocaleDateString('en-IE', { month: 'long', year: 'numeric' })}</small></article></section>
    <section className="command-risk-grid" aria-label="Operational attention queue"><a className={field?.summary.criticalIncidents ? 'critical' : ''} href="/field-control"><span>Field exceptions</span><strong>{loading ? '—' : field?.summary.openIncidents ?? 0}</strong><small>{field?.summary.criticalIncidents ?? 0} critical · {field?.summary.needsReview ?? 0} time reviews</small></a><a className={quality?.summary.overdueActions ? 'attention' : ''} href="/quality"><span>Quality actions</span><strong>{loading ? '—' : quality?.summary.openActions ?? 0}</strong><small>{quality?.summary.overdueActions ?? 0} overdue · {quality?.summary.criticalActions ?? 0} critical</small></a><a className={supplies?.items.some((item) => item.priority === 'urgent' && !['Delivered', 'Rejected', 'Cancelled'].includes(item.status)) ? 'attention' : ''} href="/supplies"><span>Material requests</span><strong>{loading ? '—' : supplies?.items.filter((item) => !['Delivered', 'Rejected', 'Cancelled'].includes(item.status)).length ?? 0}</strong><small>{supplies?.items.filter((item) => item.priority === 'urgent' && !['Delivered', 'Rejected', 'Cancelled'].includes(item.status)).length ?? 0} urgent · open replenishment work</small></a></section>
  </main>
}
