'use client'

import { useEffect, useState } from 'react'

type Visit = { id: string; scheduledStart: string; scheduledEnd: string; status: string; site: { name: string; client: { displayName: string } } }
type NoticeData = { items: Array<{ id: string; title: string; priority: string; publishedAt: string; recipients: Array<{ seenAt?: string | null; acknowledgedAt?: string | null }> }>; summary: { unread?: number; awaitingAcknowledgement?: number } }
type SupplyData = { items: Array<{ id: string; clientLocation: string; status: string; priority: string }> }

type Props = { roleLabel: string; canSchedule: boolean; canSupplies: boolean; canQuality: boolean; canTimeReview: boolean; canFinance: boolean }
async function read<T>(url: string): Promise<T | null> { const response = await fetch(url, { credentials: 'include', cache: 'no-store' }); const body = await response.json().catch(() => null); return response.ok && body?.ok ? body.data as T : null }

export default function RoleWorkspaceHome({ roleLabel, canSchedule, canSupplies, canQuality, canTimeReview, canFinance }: Props) {
  const [visits, setVisits] = useState<Visit[]>([]); const [notices, setNotices] = useState<NoticeData | null>(null); const [supplies, setSupplies] = useState<SupplyData | null>(null); const [loading, setLoading] = useState(true)
  useEffect(() => { void (async () => { setLoading(true); const now = new Date(); const to = new Date(now.getTime() + 7 * 86_400_000); const [visitData, noticeData, supplyData] = await Promise.all([canSchedule ? read<Visit[]>(`/api/visits?from=${encodeURIComponent(now.toISOString())}&to=${encodeURIComponent(to.toISOString())}`) : Promise.resolve(null), read<NoticeData>('/api/operational-notices?scope=mine'), canSupplies ? read<SupplyData>('/api/supplies?mine=true&limit=20') : Promise.resolve(null)]); setVisits(visitData ?? []); setNotices(noticeData); setSupplies(supplyData); setLoading(false) })() }, [canSchedule, canSupplies])
  const next = visits[0]
  const openRequests = supplies?.items.filter((item) => !['Delivered','Rejected','Cancelled'].includes(item.status)).length ?? 0
  return <main className="page-shell role-home"><header className="manager-home-hero"><div><span className="eyebrow">Your operational workspace · {roleLabel}</span><h1>What needs your attention</h1><p>Only the work and controls relevant to your operational role are shown here.</p></div></header><section className="role-home-grid">{canSchedule ? <article className="card role-home-primary"><span className="eyebrow">Next work</span>{loading ? <h2>Loading…</h2> : next ? <><h2>{next.site.client.displayName}</h2><p>{next.site.name} · {new Date(next.scheduledStart).toLocaleString('en-IE', { weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</p><a className="btn-primary" href="/schedule">Open my schedule</a></> : <><h2>No upcoming work</h2><p className="muted">Nothing assigned in the next seven days.</p><a className="btn-secondary" href="/schedule">Open schedule</a></>}</article> : null}<article className="card"><span className="eyebrow">Team inbox</span><strong className="role-home-number">{notices?.summary.awaitingAcknowledgement ?? 0}</strong><p className="muted">notice{(notices?.summary.awaitingAcknowledgement ?? 0) === 1 ? '' : 's'} waiting for acknowledgement</p><a className="btn-secondary" href="/communications">Open inbox</a></article>{canSupplies ? <article className="card"><span className="eyebrow">Materials</span><strong className="role-home-number">{openRequests}</strong><p className="muted">open request{openRequests === 1 ? '' : 's'}</p><a className="btn-secondary" href="/supplies">Open materials</a></article> : null}{canQuality ? <article className="card"><span className="eyebrow">Quality assurance</span><h2>Inspect & verify</h2><p className="muted">Review service outcomes and corrective actions.</p><a className="btn-secondary" href="/quality">Open quality</a></article> : null}{canTimeReview || canFinance ? <article className="card"><span className="eyebrow">Time & payroll</span><h2>{canFinance ? 'Payroll readiness' : 'Review team time'}</h2><p className="muted">Use the approved review period as the source of truth.</p><a className="btn-secondary" href="/timesheets">Open timesheets</a></article> : null}</section></main>
}
